### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by mflknr** [adjust/ios_adobe_extension#2]
Hello,

are there any plans on supporting SPM in this SDK?

Regards

**Comment by uerceg** [comment]
Hi @mflknr 

Sorry for a bit of a delay in replying on this one. Yeah, we didn't initially release this extension with SPM support in mind, but can be added. We'll try to add SPM support in our next release.

**Comment by mflknr** [comment]
Hi @uerceg 

I tried to add a `Package.swift` myself but run into some problems in a [fork](https://github.com/mflknr/ios_adobe_extension). Maybe it helps as a starting point for you, but I am sure that I am missing some stuff to set it up fully.

**Comment by uerceg** [comment]
Hey @mflknr,

Thank you for this, definitely helps. Actually we are picking up this task on our end this week to work on it. :) So should get back to you with some updates soon.

**Comment by mflknr** [comment]
That's nice to hear! The reason why I am behind this is I am migrating our project to build it with tuist, so I need the Dependency accessible as a package, XCFramework or Carthage. If you could provide a .xcframework that would also help tremendously :)

**Comment by mflknr** [comment]
Hey @uerceg 
Any news regarding the SPM integration?

Thanks

**Comment by uerceg** [comment]
Hey @mflknr,

Still work in progress. Hopefully we will have some update on this one next week. Will keep you posted.

**Comment by uerceg** [comment]
Hi @mflknr 

Thank you for your patience one more time. We have just released v1.0.4 update for the Adobe extension where we added support for Swift Package Manager. Please make sure to check newly added [README chapter](https://github.com/adjust/ios_adobe_extension#swift-package-manager-integration) about this and check if it works for you.

I'll close this issue for now, but in case you face any issues, please feel free to comment / reopen. Looking forward to hearing back from you. Cheers!
